### ISSUE TITLE
I have a problem

### ISSUE THREAD

**Issue by wesamlibya** [choirurrizal/paraminer#3]
HP Fatal error:  Uncaught Error: Call to undefined function curl_init() in /home/kali/Desktop/ntfy/paraminer/paraminer.php:47
Stack trace:
#0 /home/kali/Desktop/ntfy/paraminer/paraminer.php(99): paraminer::__try_post()
#1 /home/kali/Desktop/ntfy/paraminer/paraminer.php(116): paraminer::__run()
#2 {main}
  thrown in /home/kali/Desktop/ntfy/paraminer/paraminer.php on line 47
  
<img width="1129" alt="php" src="https://github.com/choirurrizal/paraminer/assets/95371893/c27db6e4-8ad5-433b-ad36-7e132bd5b067">

**Comment by choirurrizal** [comment]
https://www.php.net/manual/en/book.curl.php
